[package]
name = "Ora"
edition = "2024.beta"
license = " MIT"

[dependencies]
usdc = { git = "https://github.com/circlefin/stablecoin-sui.git", subdir = "packages/usdc", rev = "master" }

[addresses]
orafi = "0x15149164d86a1b58ed8f0031a685c33533ec6cd0431b12736f0ee6c58bf736d8"
